name: Deploy Api Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 프로젝트 Node 버전

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build # start 대신 build 사용

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Stop existing PM2 process
        run: pm2 delete api-server || true # 실행 중인 프로세스가 없어도 에러 무시

      - name: Start application with PM2
        run: pm2 start ecosystem.config.js

      - name: Save PM2 configuration
        run: pm2 save

      - name: Show PM2 status
        run: pm2 status