name: Deploy Api Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 프로젝트 Node 버전

      - name: Install dependencies
        run: npm ci

      - name: Stop existing PM2 process
        run: |
          pm2 delete api-server || true
          pm2 kill || true
          sleep 2

      - name: Start application with PM2
        run: pm2 start src/server.js --name "api-server"

      - name: Save PM2 configuration
        run: pm2 save

      - name: Show PM2 status
        run: pm2 status